student:
    resource: "@StudentBundle/Controller/"
    type:     annotation

teacher:
    resource: "@TeacherBundle/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout