session:
    resource: "@SessionBundle/Controller/"
    type:     annotation
    prefix:   /

student:
    resource: "@StudentBundle/Controller/"
    type:     annotation
    prefix:   /

teacher:
    resource: "@TeacherBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
