# app/config/security.yml
security:
    providers:
        in_memory:
            memory:
                users:
                    student:
                        password: student
                        roles: 'ROLE_STUDENT'
                    teacher:
                        password: teacher
                        roles: 'ROLE_TEACHER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/student, roles: ROLE_STUDENT }
        - { path: ^/teacher, roles: ROLE_TEACHER }